Beta svein
JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments pull request #122
Opened 2019-05-08 12:04 UTC by kongebra

Partially added group functions.

Mainly pull request for this:
* Report for reviews done for assignment

2019-05-08 12:44 UTC, BredeFK requested changes
* Fix the commented issues.
* Fix `SetFlash` and `GetFlash` lint error (even though you didn't create them)
* **Bonus**: Add assignment id to report name to easier separate multiple reports.
* **Also**: Remember to add meeting notes

Other than that 👉 💯 🥇 :trollface: :neckbeard:

2019-05-08 14:59 UTC, kongebra commented on webservice/template/admin/assignment/submissions.tmpl
> +            <a href="/admin/assignment/{{.Assignment.ID}}/report.xlsx" class="btn btn-primary">Download Report</a>
da0312e

2019-05-10 11:59 UTC, JohanAanesen commented on webservice/template/admin/assignment/update_new.tmpl
> +                reviewDeadlineContainer.classList.add('sr-only');
don't hide the review stuff even if it is disabled. It should be enabled/disabled by the button

2019-05-10 11:59 UTC, JohanAanesen commented on webservice/template/admin/assignment/update_new.tmpl
> +                    reviewDeadlineContainer.classList.remove('sr-only');
.

2019-05-10 11:59 UTC, JohanAanesen commented on webservice/template/admin/assignment/update_new.tmpl
> +                    reviewDeadlineContainer.classList.add('sr-only');
.

2019-05-10 11:59 UTC, JohanAanesen commented on webservice/template/admin/assignment/update_new.tmpl
> +                    submissionContainer.classList.remove('sr-only');
.

2019-05-10 11:59 UTC, JohanAanesen commented on webservice/template/admin/assignment/update_new.tmpl
> +                    submissionContainer.classList.add('sr-only');
.

2019-05-10 12:00 UTC, JohanAanesen commented on webservice/template/admin/assignment/update_new.tmpl
> +                    <button type="button" id="toggleReview" class="btn btn-danger btn-sm mb-3">Disable</button>
Se hvordan den andre update filen er, disable/enable knappen skal være over.

2019-05-10 12:01 UTC, JohanAanesen requested changes
fix assignment create og assignment update sånn den var.

2019-05-10 12:02 UTC, JohanAanesen commented on webservice/template/admin/assignment/create.tmpl
> +                reviewDeadlineContainer.classList.add('sr-only');
.

2019-05-10 12:02 UTC, JohanAanesen commented on webservice/template/admin/assignment/create.tmpl
> +                    reviewDeadlineContainer.classList.remove('sr-only');
.

2019-05-10 12:02 UTC, JohanAanesen commented on webservice/template/admin/assignment/create.tmpl
> +                    reviewDeadlineContainer.classList.add('sr-only');
.

2019-05-10 12:02 UTC, JohanAanesen commented on webservice/template/admin/assignment/create.tmpl
> +                    submissionContainer.classList.remove('sr-only');
.

2019-05-10 12:02 UTC, JohanAanesen commented on webservice/template/admin/assignment/create.tmpl
> +                    submissionContainer.classList.add('sr-only');
.

2019-05-10 12:23 UTC, JohanAanesen requested changes

2019-05-10 12:23 UTC, JohanAanesen commented on webservice/service/assignment.go
> -	return assignment.ReviewEnabled, err
This should use the ReviewEnabled variable, not check if reviewID is valid.

2019-05-10 14:58 UTC, JohanAanesen approved these changes

2019-05-13 10:57 UTC, BredeFK approved these changes

2019-05-13 10:57 UTC, merged

2019-05-13 10:58 UTC, BredeFK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Export submission/review data to excel](https://trello.com/c/8lbbmNoh/44-export-submission-review-data-to-excel)